### PR TITLE
Feature

### PR DESCRIPTION
**Pull request by DanielMitiku**
Project is ready for review!

### CODE REVIEW

**Review by Oghenebrume50 — CHANGES_REQUESTED** [review]
STATUS: Changes Required

Hi  @DanielMitiku good job man, this is awesome and neat, there are just a few changes to be made 

- The background should change for every search
change

- this task is meant to test your understanding of promises too see this                                                   
Please make changes and request for another review :slightly_smiling_face: 
Raphael Noriode :sunglasses:

**Review by Oghenebrume50 — CHANGES_REQUESTED** [review]
STATUS: Changes Required

Hi @DanielMitiku Good job man, I see the added image but it seems you forgot the second pointer use either async/await or promises see this

Please make changes and request a review 

Raphael Noriode :sunglasses:

**Comment by DanielMitiku** [comment]
Hey @Oghenebrume50, I just used Promise using the giphy API. What do you mean with your comment? Please clarify.

**Review by jofer86 — COMMENTED** [review]
## 👋 👋 Hello!! It seems your changes cover everything that my fellow TSE asked of you. It is 👍 👍  from me you may now merge! Move along!

--------------------------------------------------------------------
### Cheers, Jorge Fernando Rincón Figueroa.
Technical Support Engineer.
Slack: @jofer86.
email: jofer86@gmail.com

**Pull request merged**
